name: TooManyQuestionsCI
on: [push]
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.3
        bundler-cache: true
    - name: Run tests
      env:
        WEB_HOOK_DISCORD: $ {{ secrets.WEB_HOOK_DISCORD }} 
        USER_ID: ${{ secrets.USER_ID }}
      run: |
        cd TinkoffChat; gem install bundler; bundle install; bundle exec fastlane general_call
